default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: residents_wiki_development

test:
  <<: *default
  database: residents_wiki_test

production:
  <<: *default
  database: residents_wiki_production
  username: residents_wiki
  password: <%= ENV['RESIDENTS_WIKI_DATABASE_PASSWORD'] %>
