# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 579c0c33ad6e12a91e53e75557a44ea91f31e95de69550b29d63638da2e1ccf5ab368fd0c9a3d6d0282d4c5683c70cb4d045dea1330ceeb00998a121a1ba211e

test:
  secret_key_base: 06767979a38c17d32b86183285dc0ff697ba76f1a8c6d8f0344637246e86fca42d2f6e53f919d236a4227848659cc70b164449bdf7dd43f59b7b2697cfba83cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
